version: '3'
services:
   postgis:
       # image: mdillon/postgis
       image: skywidesoft/postgres-hstore-postgis
       environment:
           POSTGRES_USER: respa
           POSTGRES_PASSWORD: respa
           POSTGRES_DB: respa
       volumes:
           - postgis-data-volume:/var/lib/postgresql/data
       container_name: respa-db
       ports:
           - "5432:5432"

volumes:
       postgis-data-volume:
