# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-11-15 10:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Time of creation')),
                ('modified_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Time of modification')),
                ('purchase_code', models.CharField(max_length=40, verbose_name='Purchase code')),
                ('vat_percent', models.IntegerField(choices=[(0, '0'), (10, '10'), (14, '24'), (24, '24')], default=24)),
                ('price_vat', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('product_name', models.CharField(blank=True, max_length=100, verbose_name='Product name')),
                ('purchase_process_started', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Purchase process started')),
                ('purchase_process_success', models.DateTimeField(blank=True, null=True, verbose_name='Purchase process success')),
                ('purchase_process_failure', models.DateTimeField(blank=True, null=True, verbose_name='Purchase process failure')),
                ('purchase_process_notified', models.DateTimeField(blank=True, null=True, verbose_name='Purchase process notified')),
                ('purchase_process_report_seen', models.DateTimeField(blank=True, null=True, verbose_name='Purchase process notified')),
                ('payment_service_order_number', models.IntegerField(blank=True, null=True)),
                ('payment_service_timestamp', models.CharField(blank=True, max_length=100, null=True, verbose_name='Payment service timestamp')),
                ('payment_service_paid', models.CharField(blank=True, max_length=100, null=True, verbose_name='Payment service paid')),
                ('payment_service_method', models.IntegerField(blank=True, null=True)),
                ('payment_service_return_authcode', models.CharField(blank=True, max_length=100, null=True, verbose_name='Reserver address street')),
                ('finished', models.DateTimeField(blank=True, null=True, verbose_name='Purchase finished')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_modified', to=settings.AUTH_USER_MODEL, verbose_name='Modified by')),
                ('reservation', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='resources.Reservation', verbose_name='Reservation')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
