# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-11-15 13:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lpr_purchase', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='reservation',
        ),
        migrations.AlterField(
            model_name='purchase',
            name='purchase_process_report_seen',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Purchase process report seen'),
        ),
    ]
