# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-11-19 11:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lpr_purchase', '0002_auto_20181115_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='payment_address',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Payment link'),
        ),
    ]
