# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-11-19 13:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lpr_purchase', '0003_purchase_payment_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='status',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
