# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-11-20 08:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lpr_purchase', '0004_purchase_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='ceepos_reference',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
