# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-11-20 08:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lpr_purchase', '0005_purchase_ceepos_reference'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='finished',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='payment_service_method',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='payment_service_order_number',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='payment_service_paid',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='payment_service_return_authcode',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='payment_service_timestamp',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='purchase_process_notified',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='purchase_process_report_seen',
        ),
    ]
