# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-11-15 10:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0067_auto_20181115_1258'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='ceepos_payment_required',
            field=models.BooleanField(default=False, verbose_name='Ceepos payment required'),
        ),
        migrations.AddField(
            model_name='resource',
            name='product_code',
            field=models.CharField(default='', max_length=25, verbose_name='Product code'),
        ),
        migrations.AddField(
            model_name='resourcegroup',
            name='ceepos_payment_required',
            field=models.BooleanField(default=False, verbose_name='Ceepos payment required'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='state',
            field=models.CharField(choices=[('created', 'created'), ('cancelled', 'cancelled'), ('confirmed', 'confirmed'), ('denied', 'denied'), ('requested', 'requested'), ('pending', 'pending')], default='confirmed', max_length=16, verbose_name='State'),
        ),
    ]
