# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-11-15 13:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lpr_purchase', '0002_auto_20181115_1524'),
        ('resources', '0068_add_lpr_purchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='purchase',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lpr_purchase.Purchase', verbose_name='Purchase'),
        ),
    ]
