# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-11-27 08:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0071_auto_20181115_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='product_code',
            field=models.CharField(blank=True, default='', max_length=25, verbose_name='Product code'),
        ),
    ]
