# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-11-30 11:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0072_auto_20181127_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='purchase',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservation', to='lpr_purchase.Purchase', verbose_name='Purchase'),
        ),
    ]
