# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-12-05 07:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0073_auto_20181130_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='purchase',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservation', to='lpr_purchase.Purchase', verbose_name='Purchase'),
        ),
    ]
