# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-04-24 08:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0074_auto_20181205_0904'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='staff_event',
            field=models.BooleanField(default=False, verbose_name='Staff event'),
        ),
    ]
