# Generated by Django 1.11.29 on 2020-06-10 13:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0075_auto_20190424_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='manual_price',
            field=models.CharField(blank=True, max_length=30, verbose_name='Manual price'),
        ),
    ]
